library(rgdal)
library(raster)
library(sp)
library(dismo)

#make sure to cd~ before running if done interactively. Sh submission script has this included. 
prec_r_1 <- raster("project/CHELSA/prec/uganda_kenya_clips/CHELSA_prec_2008_01_V1.2.1_UgandaKenyaClip.tif")
prec_r_2 <- raster("project/CHELSA/prec/uganda_kenya_clips/CHELSA_prec_2008_02_V1.2.1_UgandaKenyaClip.tif")
prec_r_3 <- raster("project/CHELSA/prec/uganda_kenya_clips/CHELSA_prec_2008_03_V1.2.1_UgandaKenyaClip.tif")
prec_r_4 <- raster("project/CHELSA/prec/uganda_kenya_clips/CHELSA_prec_2008_04_V1.2.1_UgandaKenyaClip.tif")
prec_r_5 <- raster("project/CHELSA/prec/uganda_kenya_clips/CHELSA_prec_2008_05_V1.2.1_UgandaKenyaClip.tif")
prec_r_6 <- raster("project/CHELSA/prec/uganda_kenya_clips/CHELSA_prec_2008_06_V1.2.1_UgandaKenyaClip.tif")
prec_r_7 <- raster("project/CHELSA/prec/uganda_kenya_clips/CHELSA_prec_2008_07_V1.2.1_UgandaKenyaClip.tif")
prec_r_8 <- raster("project/CHELSA/prec/uganda_kenya_clips/CHELSA_prec_2008_08_V1.2.1_UgandaKenyaClip.tif")
prec_r_9 <- raster("project/CHELSA/prec/uganda_kenya_clips/CHELSA_prec_2008_09_V1.2.1_UgandaKenyaClip.tif")
prec_r_10 <- raster("project/CHELSA/prec/uganda_kenya_clips/CHELSA_prec_2008_10_V1.2.1_UgandaKenyaClip.tif")
prec_r_11 <- raster("project/CHELSA/prec/uganda_kenya_clips/CHELSA_prec_2008_11_V1.2.1_UgandaKenyaClip.tif")
prec_r_12 <- raster("project/CHELSA/prec/uganda_kenya_clips/CHELSA_prec_2008_12_V1.2.1_UgandaKenyaClip.tif")

prec_uganda <-stack(prec_r_1,prec_r_2,prec_r_3,prec_r_4,prec_r_5,prec_r_6,prec_r_7,prec_r_8,prec_r_9,prec_r_10,prec_r_11,prec_r_12)
proj4string(prec_uganda)<-CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

tmax_r_1 <- raster("project/CHELSA/tmax/uganda_kenya_clips/CHELSA_tmax_2008_01_V1.2.1_UgandaKenyaClip.tif")
tmax_r_2 <- raster("project/CHELSA/tmax/uganda_kenya_clips/CHELSA_tmax_2008_02_V1.2.1_UgandaKenyaClip.tif")
tmax_r_3 <- raster("project/CHELSA/tmax/uganda_kenya_clips/CHELSA_tmax_2008_03_V1.2.1_UgandaKenyaClip.tif")
tmax_r_4 <- raster("project/CHELSA/tmax/uganda_kenya_clips/CHELSA_tmax_2008_04_V1.2.1_UgandaKenyaClip.tif")
tmax_r_5 <- raster("project/CHELSA/tmax/uganda_kenya_clips/CHELSA_tmax_2008_05_V1.2.1_UgandaKenyaClip.tif")
tmax_r_6 <- raster("project/CHELSA/tmax/uganda_kenya_clips/CHELSA_tmax_2008_06_V1.2.1_UgandaKenyaClip.tif")
tmax_r_7 <- raster("project/CHELSA/tmax/uganda_kenya_clips/CHELSA_tmax_2008_07_V1.2.1_UgandaKenyaClip.tif")
tmax_r_8 <- raster("project/CHELSA/tmax/uganda_kenya_clips/CHELSA_tmax_2008_08_V1.2.1_UgandaKenyaClip.tif")
tmax_r_9 <- raster("project/CHELSA/tmax/uganda_kenya_clips/CHELSA_tmax_2008_09_V1.2.1_UgandaKenyaClip.tif")
tmax_r_10 <- raster("project/CHELSA/tmax/uganda_kenya_clips/CHELSA_tmax_2008_10_V1.2.1_UgandaKenyaClip.tif")
tmax_r_11 <- raster("project/CHELSA/tmax/uganda_kenya_clips/CHELSA_tmax_2008_11_V1.2.1_UgandaKenyaClip.tif")
tmax_r_12 <- raster("project/CHELSA/tmax/uganda_kenya_clips/CHELSA_tmax_2008_12_V1.2.1_UgandaKenyaClip.tif")

tmax_uganda <-stack(tmax_r_1,tmax_r_2,tmax_r_3,tmax_r_4,tmax_r_5,tmax_r_6,tmax_r_7,tmax_r_8,tmax_r_9,tmax_r_10,tmax_r_11,tmax_r_12)
proj4string(tmax_uganda)<-CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

tmin_r_1 <- raster("project/CHELSA/tmin/uganda_kenya_clips/CHELSA_tmin_2008_01_V1.2.1_UgandaKenyaClip.tif")
tmin_r_2 <- raster("project/CHELSA/tmin/uganda_kenya_clips/CHELSA_tmin_2008_02_V1.2.1_UgandaKenyaClip.tif")
tmin_r_3 <- raster("project/CHELSA/tmin/uganda_kenya_clips/CHELSA_tmin_2008_03_V1.2.1_UgandaKenyaClip.tif")
tmin_r_4 <- raster("project/CHELSA/tmin/uganda_kenya_clips/CHELSA_tmin_2008_04_V1.2.1_UgandaKenyaClip.tif")
tmin_r_5 <- raster("project/CHELSA/tmin/uganda_kenya_clips/CHELSA_tmin_2008_05_V1.2.1_UgandaKenyaClip.tif")
tmin_r_6 <- raster("project/CHELSA/tmin/uganda_kenya_clips/CHELSA_tmin_2008_06_V1.2.1_UgandaKenyaClip.tif")
tmin_r_7 <- raster("project/CHELSA/tmin/uganda_kenya_clips/CHELSA_tmin_2008_07_V1.2.1_UgandaKenyaClip.tif")
tmin_r_8 <- raster("project/CHELSA/tmin/uganda_kenya_clips/CHELSA_tmin_2008_08_V1.2.1_UgandaKenyaClip.tif")
tmin_r_9 <- raster("project/CHELSA/tmin/uganda_kenya_clips/CHELSA_tmin_2008_09_V1.2.1_UgandaKenyaClip.tif")
tmin_r_10 <- raster("project/CHELSA/tmin/uganda_kenya_clips/CHELSA_tmin_2008_10_V1.2.1_UgandaKenyaClip.tif")
tmin_r_11 <- raster("project/CHELSA/tmin/uganda_kenya_clips/CHELSA_tmin_2008_11_V1.2.1_UgandaKenyaClip.tif")
tmin_r_12 <- raster("project/CHELSA/tmin/uganda_kenya_clips/CHELSA_tmin_2008_12_V1.2.1_UgandaKenyaClip.tif")

tmin_uganda <-stack(tmin_r_1,tmin_r_2,tmin_r_3,tmin_r_4,tmin_r_5,tmin_r_6,tmin_r_7,tmin_r_8,tmin_r_9,tmin_r_10,tmin_r_11,tmin_r_12)
proj4string(tmin_uganda)<-CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

biovar_uganda_2008 <- biovars(prec_uganda,tmin_uganda,tmax_uganda)
#repetitive definition of projection, but added in case (this line is sufficent for the output to be in the desired CRS)
proj4string(biovar_uganda_2008)<-CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

writeRaster(biovar_uganda_2008,"/home/fas/caccone/apb56/project/CHELSA/biovars/UgandaBiovarsFuture",format="GTiff")